# Generated by Django 6.0 on 2025-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticketcomment_userid_ticketcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('API', 'API'), ('SMS', 'SMS'), ('System', 'System'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Escalated', 'Escalated'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Open', max_length=20),
        ),
    ]
