# Generated by Django 6.0 on 2025-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_subscriptionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_pending_payment', 'Approved (Payment Pending)'), ('approved', 'Approved (Active)'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
