# Generated by Django 6.0 on 2025-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_protected',
            field=models.BooleanField(default=False, help_text="If True, API updates will not overwrite this flight's data."),
        ),
    ]
